# This playbook is used to merge all part 
# configuration files into one large file ready to 
# be delivered to the Junos device
- name: Apply configuration
  hosts: all
  connection: local
  gather_facts: no
  vars_prompt:
      - name: USERNAME
        prompt: Radius user
        private: no
      - name: PASSWORD
        prompt: Password
        private: yes
  tasks:
      - name: assembling part configuration files and merging to one file
        assemble: src={{ build_dir }} dest={{ junos_conf }}

      - name: Pushing configuration over netconf
        junos_install_config: 
            host={{ inventory_hostname }}
            port=22
            user={{ USERNAME }}
            passwd={{ PASSWORD }}
            file={{ junos_conf }}
            overwrite=no
            logfile=./logging/changes.log
